=== JuliaQUBO/QUBO.jl/QUBOTools.jl/src/models/bqpjson/bqpjson.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Binary Quadratic Program Schema",
    "type": "object",
    "required": [
        "version",
        "id",
        "variable_ids",
        "variable_domain",
        "scale",
        "offset",
        "linear_terms",
        "quadratic_terms",
        "metadata"
    ],
    "properties": {
        "version": {
            "type": "string",
            "enum": [
                "1.0.0"
            ]
        },
        "id": {
            "type": "integer",
            "minimum": 0
        },
        "metadata": {
            "type": "object",
            "properties": {
                "dw_url": {
                    "type": "string"
                },
                "dw_solver_name": {
                    "type": "string"
                },
                "dw_chip_id": {
                    "type": "string"
                },
                "chimera_cell_size": {
                    "type": "integer",
                    "minimum": 0
                },
                "chimera_degree": {
                    "type": "integer",
                    "minimum": 0
                },
                "generated": {
                    "type": "string"
                },
                "dwig_generator": {
                    "type": "string"
                }
            }
        },
        "variable_ids": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 0
            }
        },
        "variable_domain": {
            "type": "string",
            "enum": [
                "spin",
                "boolean"
            ]
        },
        "scale": {
            "type": "number"
        },
        "offset": {
            "type": "number"
        },
        "linear_terms": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "coeff"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "coeff": {
                        "type": "number"
                    }
                }
            }
        },
        "quadratic_terms": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id_head",
                    "id_tail",
                    "coeff"
                ],
                "properties": {
                    "id_head": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "id_tail": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "coeff": {
                        "type": "number"
                    }
                }
            }
        },
        "description": {
            "type": "string"
        },
        "solutions": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "assignment"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "description": {
                        "type": "string"
                    },
                    "evaluation": {
                        "type": "number"
                    },
                    "assignment": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "id",
                                "value"
                            ],
                            "properties": {
                                "id": {
                                    "type": "integer",
                                    "minimum": 0
                                },
                                "value": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== JuliaQUBO/QUBO.jl/QUBOTools.jl/test/data/01/bool.json
{
    "description": "Model 1 ~ Simple model with linear terms",
    "id": 1,
    "linear_terms": [
        {
            "id": 2,
            "coeff": 1.3
        },
        {
            "id": 6,
            "coeff": -0.7
        }
    ],
    "metadata": {},
    "offset": 0.0,
    "quadratic_terms": [],
    "scale": 1.0,
    "variable_domain": "boolean",
    "variable_ids": [
        2,
        4,
        6
    ],
    "version": "1.0.0"
}

=== JuliaQUBO/QUBO.jl/QUBOTools.jl/test/data/02/bool.json
{
    "scale": 2.7,
    "id": 2,
    "version": "1.0.0",
    "description": "Model 2 ~ Simple model with solutions",
    "linear_terms": [
        {
            "id": 1,
            "coeff": 0.0
        },
        {
            "id": 3,
            "coeff": 0.4
        },
        {
            "id": 5,
            "coeff": -4.4
        }
    ],
    "offset": 1.93,
    "quadratic_terms": [
        {
            "id_head": 1,
            "coeff": -0.8,
            "id_tail": 3
        },
        {
            "id_head": 1,
            "coeff": 6.0,
            "id_tail": 5
        }
    ],
    "variable_domain": "boolean",
    "variable_ids": [
        1,
        3,
        5
    ],
    "metadata": {},
    "solutions": [
        {
            "evaluation": 6.291,
            "id": 0,
            "assignment": [
                {
                    "id": 1,
                    "value": 0
                },
                {
                    "id": 3,
                    "value": 1
                },
                {
                    "id": 5,
                    "value": 0
                }
            ],
            "description": "first solution"
        },
        {
            "evaluation": 9.531,
            "id": 1,
            "assignment": [
                {
                    "id": 1,
                    "value": 1
                },
                {
                    "id": 3,
                    "value": 0
                },
                {
                    "id": 5,
                    "value": 1
                }
            ],
            "description": "second solution"
        }
    ]
}

=== JuliaQUBO/QUBO.jl/QUBOTools.jl/test/data/04/bool.json
{
	"description": "Model 2 ~ This case tests the hfs translator. Both in recovering integer coefficents and computing an effective chimera degree.",
	"id": 2,
	"linear_terms": [
		{
			"coeff": 1.0,
			"id": 0
		},
		{
			"coeff": -1.0,
			"id": 1
		},
		{
			"coeff": 2.5,
			"id": 2
		},
		{
			"coeff": -4.75,
			"id": 3
		},
		{
			"coeff": -1.0,
			"id": 4
		},
		{
			"coeff": 2.0,
			"id": 5
		},
		{
			"coeff": 1.75,
			"id": 6
		},
		{
			"coeff": -2.25,
			"id": 7
		},
		{
			"coeff": 2.5,
			"id": 8
		},
		{
			"coeff": -3.5,
			"id": 9
		},
		{
			"coeff": 3.0,
			"id": 10
		},
		{
			"coeff": -1.5,
			"id": 11
		},
		{
			"coeff": -2.75,
			"id": 12
		},
		{
			"coeff": 1.25,
			"id": 13
		},
		{
			"coeff": 4.75,
			"id": 14
		},
		{
			"coeff": 1.25,
			"id": 15
		},
		{
			"coeff": -2.0,
			"id": 96
		},
		{
			"coeff": 3.5,
			"id": 97
		},
		{
			"coeff": 1.25,
			"id": 98
		},
		{
			"coeff": 3.0,
			"id": 99
		},
		{
			"coeff": 5.5,
			"id": 100
		},
		{
			"coeff": 1.0,
			"id": 101
		},
		{
			"coeff": 1.75,
			"id": 102
		},
		{
			"coeff": -0.75,
			"id": 103
		},
		{
			"coeff": -3.25,
			"id": 104
		},
		{
			"coeff": 1.25,
			"id": 105
		},
		{
			"coeff": -4.75,
			"id": 106
		},
		{
			"coeff": -5.0,
			"id": 107
		},
		{
			"coeff": -3.0,
			"id": 108
		},
		{
			"coeff": -5.0,
			"id": 109
		},
		{
			"coeff": -1.5,
			"id": 110
		},
		{
			"coeff": -3.5,
			"id": 111
		}
	],
	"metadata": {
		"chimera_cell_size": 8,
		"chimera_degree": 12
	},
	"offset": 2.375,
	"quadratic_terms": [
		{
			"coeff": 3.0,
			"id_head": 4,
			"id_tail": 0
		},
		{
			"coeff": -3.0,
			"id_head": 5,
			"id_tail": 0
		},
		{
			"coeff": 1.5,
			"id_head": 6,
			"id_tail": 0
		},
		{
			"coeff": 2.0,
			"id_head": 7,
			"id_tail": 0
		},
		{
			"coeff": -3.0,
			"id_head": 96,
			"id_tail": 0
		},
		{
			"coeff": 3.5,
			"id_head": 4,
			"id_tail": 1
		},
		{
			"coeff": 0.5,
			"id_head": 5,
			"id_tail": 1
		},
		{
			"coeff": -2.0,
			"id_head": 6,
			"id_tail": 1
		},
		{
			"coeff": -0.5,
			"id_head": 7,
			"id_tail": 1
		},
		{
			"coeff": -2.0,
			"id_head": 97,
			"id_tail": 1
		},
		{
			"coeff": -3.0,
			"id_head": 4,
			"id_tail": 2
		},
		{
			"coeff": -2.5,
			"id_head": 5,
			"id_tail": 2
		},
		{
			"coeff": -1.0,
			"id_head": 6,
			"id_tail": 2
		},
		{
			"coeff": -0.5,
			"id_head": 7,
			"id_tail": 2
		},
		{
			"coeff": 1.0,
			"id_head": 98,
			"id_tail": 2
		},
		{
			"coeff": -3.5,
			"id_head": 4,
			"id_tail": 3
		},
		{
			"coeff": 3.0,
			"id_head": 5,
			"id_tail": 3
		},
		{
			"coeff": 3.5,
			"id_head": 6,
			"id_tail": 3
		},
		{
			"coeff": 2.0,
			"id_head": 7,
			"id_tail": 3
		},
		{
			"coeff": 3.0,
			"id_head": 99,
			"id_tail": 3
		},
		{
			"coeff": 3.0,
			"id_head": 12,
			"id_tail": 4
		},
		{
			"coeff": -1.5,
			"id_head": 13,
			"id_tail": 5
		},
		{
			"coeff": -2.0,
			"id_head": 14,
			"id_tail": 6
		},
		{
			"coeff": 2.0,
			"id_head": 15,
			"id_tail": 7
		},
		{
			"coeff": 2.0,
			"id_head": 12,
			"id_tail": 8
		},
		{
			"coeff": -1.5,
			"id_head": 13,
			"id_tail": 8
		},
		{
			"coeff": -1.5,
			"id_head": 14,
			"id_tail": 8
		},
		{
			"coeff": -3.5,
			"id_head": 15,
			"id_tail": 8
		},
		{
			"coeff": -3.5,
			"id_head": 104,
			"id_tail": 8
		},
		{
			"coeff": -1.0,
			"id_head": 12,
			"id_tail": 9
		},
		{
			"coeff": 3.0,
			"id_head": 13,
			"id_tail": 9
		},
		{
			"coeff": 3.0,
			"id_head": 14,
			"id_tail": 9
		},
		{
			"coeff": 1.0,
			"id_head": 15,
			"id_tail": 9
		},
		{
			"coeff": -1.5,
			"id_head": 105,
			"id_tail": 9
		},
		{
			"coeff": -3.5,
			"id_head": 12,
			"id_tail": 10
		},
		{
			"coeff": -1.0,
			"id_head": 13,
			"id_tail": 10
		},
		{
			"coeff": -3.5,
			"id_head": 14,
			"id_tail": 10
		},
		{
			"coeff": 3.0,
			"id_head": 15,
			"id_tail": 10
		},
		{
			"coeff": 2.0,
			"id_head": 106,
			"id_tail": 10
		},
		{
			"coeff": 2.0,
			"id_head": 12,
			"id_tail": 11
		},
		{
			"coeff": 0.5,
			"id_head": 13,
			"id_tail": 11
		},
		{
			"coeff": -3.0,
			"id_head": 14,
			"id_tail": 11
		},
		{
			"coeff": -3.0,
			"id_head": 15,
			"id_tail": 11
		},
		{
			"coeff": 3.5,
			"id_head": 107,
			"id_tail": 11
		},
		{
			"coeff": 1.5,
			"id_head": 100,
			"id_tail": 96
		},
		{
			"coeff": 3.0,
			"id_head": 101,
			"id_tail": 96
		},
		{
			"coeff": -1.0,
			"id_head": 102,
			"id_tail": 96
		},
		{
			"coeff": 0.5,
			"id_head": 103,
			"id_tail": 96
		},
		{
			"coeff": -2.5,
			"id_head": 100,
			"id_tail": 97
		},
		{
			"coeff": -3.5,
			"id_head": 101,
			"id_tail": 97
		},
		{
			"coeff": -4.0,
			"id_head": 102,
			"id_tail": 97
		},
		{
			"coeff": 1.0,
			"id_head": 103,
			"id_tail": 97
		},
		{
			"coeff": -1.5,
			"id_head": 100,
			"id_tail": 98
		},
		{
			"coeff": -4.0,
			"id_head": 101,
			"id_tail": 98
		},
		{
			"coeff": 2.0,
			"id_head": 102,
			"id_tail": 98
		},
		{
			"coeff": 1.5,
			"id_head": 103,
			"id_tail": 98
		},
		{
			"coeff": -2.0,
			"id_head": 100,
			"id_tail": 99
		},
		{
			"coeff": -2.5,
			"id_head": 101,
			"id_tail": 99
		},
		{
			"coeff": -1.5,
			"id_head": 102,
			"id_tail": 99
		},
		{
			"coeff": -1.5,
			"id_head": 103,
			"id_tail": 99
		},
		{
			"coeff": -4.0,
			"id_head": 108,
			"id_tail": 100
		},
		{
			"coeff": 4.0,
			"id_head": 109,
			"id_tail": 101
		},
		{
			"coeff": -1.0,
			"id_head": 110,
			"id_tail": 102
		},
		{
			"coeff": 1.5,
			"id_head": 111,
			"id_tail": 103
		},
		{
			"coeff": 3.0,
			"id_head": 108,
			"id_tail": 104
		},
		{
			"coeff": 3.5,
			"id_head": 109,
			"id_tail": 104
		},
		{
			"coeff": 2.0,
			"id_head": 110,
			"id_tail": 104
		},
		{
			"coeff": 3.5,
			"id_head": 111,
			"id_tail": 104
		},
		{
			"coeff": 3.0,
			"id_head": 108,
			"id_tail": 105
		},
		{
			"coeff": 3.0,
			"id_head": 109,
			"id_tail": 105
		},
		{
			"coeff": -4.0,
			"id_head": 110,
			"id_tail": 105
		},
		{
			"coeff": -4.0,
			"id_head": 111,
			"id_tail": 105
		},
		{
			"coeff": 4.0,
			"id_head": 108,
			"id_tail": 106
		},
		{
			"coeff": 1.5,
			"id_head": 109,
			"id_tail": 106
		},
		{
			"coeff": 4.0,
			"id_head": 110,
			"id_tail": 106
		},
		{
			"coeff": 2.0,
			"id_head": 111,
			"id_tail": 106
		},
		{
			"coeff": -2.5,
			"id_head": 108,
			"id_tail": 107
		},
		{
			"coeff": 1.0,
			"id_head": 109,
			"id_tail": 107
		},
		{
			"coeff": 3.0,
			"id_head": 110,
			"id_tail": 107
		},
		{
			"coeff": 1.0,
			"id_head": 111,
			"id_tail": 107
		}
	],
	"scale": 1.0,
	"variable_domain": "boolean",
	"variable_ids": [
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		96,
		97,
		98,
		99,
		100,
		101,
		102,
		103,
		104,
		105,
		106,
		107,
		108,
		109,
		110,
		111
	],
	"version": "1.0.0"
}

=== JuliaQUBO/QUBO.jl/QUBOTools.jl/test/data/02/spin.json
{
	"id": 2,
	"description": "Model 2 ~ Simple model with solutions",
	"linear_terms": [
		{
			"coeff": 1.3,
			"id": 1
		},
		{
			"coeff": -0.7,
			"id": 5
		}
	],
	"metadata": {},
	"offset": 1.23,
	"quadratic_terms": [
		{
			"coeff": -0.2,
			"id_head": 3,
			"id_tail": 1
		},
		{
			"coeff": 1.5,
			"id_head": 5,
			"id_tail": 1
		}
	],
	"scale": 2.7,
	"variable_domain": "spin",
	"variable_ids": [
		1,
		3,
		5
	],
	"version": "1.0.0",
	"solutions": [
		{
			"id": 0,
			"description": "first solution",
			"evaluation": 6.291,
			"assignment": [
				{
					"id": 1,
					"value": -1
				},
				{
					"id": 3,
					"value": 1
				},
				{
					"id": 5,
					"value": -1
				}
			]
		},
		{
			"id": 1,
			"description": "second solution",
			"evaluation": 9.531,
			"assignment": [
				{
					"id": 1,
					"value": 1
				},
				{
					"id": 3,
					"value": -1
				},
				{
					"id": 5,
					"value": 1
				}
			]
		}
	]
}

=== JuliaQUBO/QUBO.jl/QUBOTools.jl/test/data/03/spin.json
{
  "id": 3,
  "version": "1.0.0",
  "variable_domain": "spin",
  "variable_ids": [
    2,
    4,
    6
  ],
  "scale": 2.7,
  "offset": 1.23,
  "linear_terms": [
    {
      "coeff": 1.3,
      "id": 2
    },
    {
      "coeff": -0.7,
      "id": 6
    }
  ],
  "metadata": {
    "some_key_1": "any value",
    "some_key_2": 0.3,
    "some_key_3": null,
    "some_key_4": [
      "one",
      2,
      3.7,
      null
    ]
  },
  "quadratic_terms": [
    {
      "coeff": -0.2,
      "id_head": 4,
      "id_tail": 2
    },
    {
      "coeff": 1.5,
      "id_head": 6,
      "id_tail": 2
    }
  ],
  "description": "Model 3 ~ Simple model with quadratic terms and metadata"
}

=== JuliaQUBO/QUBO.jl/QUBOTools.jl/test/data/03/bool.json
{
	"id": 3,
	"version": "1.0.0",
	"variable_ids": [
		2,
		4,
		6
	],
	"variable_domain": "boolean",
	"scale": 2.7,
	"offset": 1.93,
	"linear_terms": [
		{
			"id": 2,
			"coeff": 0.0
		},
		{
			"id": 4,
			"coeff": 0.4
		},
		{
			"id": 6,
			"coeff": -4.4
		}
	],
	"quadratic_terms": [
		{
			"id_head": 2,
			"coeff": -0.8,
			"id_tail": 4
		},
		{
			"id_head": 2,
			"coeff": 6.0,
			"id_tail": 6
		}
	],
	"metadata": {
		"some_key_1": "any value",
		"some_key_2": 0.3,
		"some_key_3": null,
		"some_key_4": [
			"one",
			2,
			3.7,
			null
		]
	},
	"description": "Model 3 ~ Simple model with quadratic terms and metadata"
}
